// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOL1cks-B51Jph2HX4EAruzo06zrxLdms',
    appId: '1:390203078576:web:c95b56b16e0c9db831c875',
    messagingSenderId: '390203078576',
    projectId: 'praca-inz-f9c9d',
    authDomain: 'praca-inz-f9c9d.firebaseapp.com',
    storageBucket: 'praca-inz-f9c9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjERFIArq733gs59mM4U-SUAq4KSjC6yg',
    appId: '1:390203078576:android:24515692a3aebe2d31c875',
    messagingSenderId: '390203078576',
    projectId: 'praca-inz-f9c9d',
    storageBucket: 'praca-inz-f9c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy09E0b7tKOcUfk6EaIcjQmV2fwSt3Sws',
    appId: '1:390203078576:ios:fc6d5ecf3d53d1bf31c875',
    messagingSenderId: '390203078576',
    projectId: 'praca-inz-f9c9d',
    storageBucket: 'praca-inz-f9c9d.appspot.com',
    iosBundleId: 'com.example.projektInz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy09E0b7tKOcUfk6EaIcjQmV2fwSt3Sws',
    appId: '1:390203078576:ios:fc6d5ecf3d53d1bf31c875',
    messagingSenderId: '390203078576',
    projectId: 'praca-inz-f9c9d',
    storageBucket: 'praca-inz-f9c9d.appspot.com',
    iosBundleId: 'com.example.projektInz',
  );
}
